name: basic_feed_fetcher
description: An all-inclusive plugin, for fetching your own posts, from Facebook, Instagram and Twitter.
version: 0.0.1+2
repository: 'https://github.com/AhalDentalClinic/basic_feed_fetcher'
homepage: 'https://github.com/AhalDentalClinic/basic_feed_fetcher'
issue_tracker: 'https://github.com/AhalDentalClinic/basic_feed_fetcher/issues'
documentation: 'https://github.com/AhalDentalClinic/basic_feed_fetcher'
platforms:
  android:
  ios:

publish_to:


environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.ahaldental.basic_feed_fetcher
        pluginClass: BasicFeedFetcherPlugin
      ios:
        pluginClass: BasicFeedFetcherPlugin
